# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://booya-at.github.io/paraBEM/
baseurl:             ''

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Mark Otto
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
